jetstream:
  image:
    repository: nresare/jetstream-controller
    tag: v0.24.0-noa.1
  nats:
    url: nats://nats.nats.svc
  controlLoop: true
serviceAccountAnnotations:
  nats.io/allowed-pub-subjects: "$JS.ACK.>,$JS.API.>"
  nats.io/allowed-sub-subjects: "$JS.API.>"
