config:
  cluster:
    enabled: true
    replicas: 3
  jetstream:
    enabled: true
    fileStore:
      enabled: true
      pvc:
        enabled: true
        size: 5Gi
  resolver:
    enabled: true
    merge:
      type: full
    pvc:
      enabled: true
      size: 100Mi

  merge:
    # Operator configuration (embedded JWT)
    operator: eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJqdGkiOiJTQklBSVMyQ00yNE5NUzNOVkYzSURPSTRWV1ZFV0ZGVFBVRUVIUlM1NFIyU1FNS1hVTlFBIiwiaWF0IjoxNzg1NjgwODQxLCJpc3MiOiJPRFVTTzdDNlFXRlg0RTNLMkJGRVlLNFhONUNZRFlBQlVZTEIyQlBIRDRQSEVORDNRNkc2NDY0ViIsIm5hbWUiOiJLTVMtT3BlcmF0b3IiLCJzdWIiOiJPRFVTTzdDNlFXRlg0RTNLMkJGRVlLNFhONUNZRFlBQlVZTEIyQlBIRDRQSEVORDNRNkc2NDY0ViIsIm5hdHMiOnsic3lzdGVtX2FjY291bnQiOiJBQ0o1NUdTVTVENFdJQUlRMlNITTdLWEpYTFRVN1pTQjJPN1RRWjRYREJJS0tIWlZBMjU1NkxWTiIsInR5cGUiOiJvcGVyYXRvciIsInZlcnNpb24iOjJ9fQ.KXqmTuCbX2beXGq0js_IGQhxmyoEUIMa-pyD1LHjwPii-9bu5pDJnkB7s1C2VBAyelW5sRPiLHPiDq2nc52rCQ

    # System account
    system_account: ACJ55GSU5D4WIAIQ2SHM7KXJXLTU7ZSB2O7TQZ4XDBIKKHZVA2556LVN

    # Default sentinel user (for auth callout)
    default_sentinel: eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJqdGkiOiJRS0YzUkxGSFlQS1pTMkhONFpLVFVaQlJJN1pRRlJGNFU2WVo2Wk1NVFQ2TFhLV1hZNDNBIiwiaWF0IjoxNzg1NjgwODQxLCJpc3MiOiJBQkRBWjJHTFNVQzJUMlVRRFdJRUNBNUlMSTZKRFBGNFVUUVhURFJVNUNLSldMWFFBNUpLVlAzSSIsIm5hbWUiOiJzZW50aW5lbCIsInN1YiI6IlVEN0hJMjRISjVSVklCNktRSTJLR0QyVVFEQUpWT0pOQ1RVUEhDWkhMU1hMWElMQUdIQ01aU1FIIiwibmF0cyI6eyJwdWIiOnsiZGVueSI6WyJcdTAwM2UiXX0sInN1YiI6eyJkZW55IjpbIlx1MDAzZSJdfSwic3VicyI6LTEsImRhdGEiOi0xLCJwYXlsb2FkIjotMSwiYmVhcmVyX3Rva2VuIjp0cnVlLCJ0eXBlIjoidXNlciIsInZlcnNpb24iOjJ9fQ.t8ac5kTEN9eRmZ9locYW31bB9qMVmEvRiXAbpe3Qe_m36u3w4_Je2SX80up2KH2coviYC9hcixwbQheZ2KgxAA

    # Resolver preload for accounts (loaded at startup)
    resolver_preload:
      # SYS Account
      ACJ55GSU5D4WIAIQ2SHM7KXJXLTU7ZSB2O7TQZ4XDBIKKHZVA2556LVN: eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJqdGkiOiJTR0xEWlRCUEJYNU1aNTNUNVVUSElVMlA3WUpUNTJZVEZFTU5PSTdNV0NLTFRRN1BWVlFRIiwiaWF0IjoxNzg1NjgwODQxLCJpc3MiOiJPRFVTTzdDNlFXRlg0RTNLMkJGRVlLNFhONUNZRFlBQlVZTEIyQlBIRDRQSEVORDNRNkc2NDY0ViIsIm5hbWUiOiJTWVMiLCJzdWIiOiJBQ0o1NUdTVTVENFdJQUlRMlNITTdLWEpYTFRVN1pTQjJPN1RRWjRYREJJS0tIWlZBMjU1NkxWTiIsIm5hdHMiOnsibGltaXRzIjp7InN1YnMiOi0xLCJkYXRhIjotMSwicGF5bG9hZCI6LTEsImltcG9ydHMiOi0xLCJleHBvcnRzIjotMSwid2lsZGNhcmRzIjp0cnVlLCJjb25uIjotMSwibGVhZiI6LTF9LCJkZWZhdWx0X3Blcm1pc3Npb25zIjp7InB1YiI6e30sInN1YiI6e319LCJhdXRob3JpemF0aW9uIjp7fSwidHlwZSI6ImFjY291bnQiLCJ2ZXJzaW9uIjoyfX0.qdHAkZ4ZQHqGcJObIF67cNZ8KUuWemM09KCsrYeF2sQB71yNBRJpWeKCbtW4E-lZsQZ8VENez_JeQ1VtFET3CQ
      # AUTH Account
      ABDAZ2GLSUC2T2UQDWIECA5ILI6JDPF4UTQXTDRU5CKJWLXQA5JKVP3I: eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ.eyJqdGkiOiJPWkNSWDI2V0FaS0ZHVVNGTUJLR1lSMzVIUEk1RlNMTVFNQTJGN0hVQktERjZaSFJLWUxBIiwiaWF0IjoxNzg1NjgwODQxLCJpc3MiOiJPRFVTTzdDNlFXRlg0RTNLMkJGRVlLNFhONUNZRFlBQlVZTEIyQlBIRDRQSEVORDNRNkc2NDY0ViIsIm5hbWUiOiJBVVRIIiwic3ViIjoiQUJEQVoyR0xTVUMyVDJVUURXSUVDQTVJTEk2SkRQRjRVVFFYVERSVTVDS0pXTFhRQTVKS1ZQM0kiLCJuYXRzIjp7ImxpbWl0cyI6eyJzdWJzIjotMSwiZGF0YSI6LTEsInBheWxvYWQiOi0xLCJpbXBvcnRzIjotMSwiZXhwb3J0cyI6LTEsIndpbGRjYXJkcyI6dHJ1ZSwiY29ubiI6LTEsImxlYWYiOi0xfSwiZGVmYXVsdF9wZXJtaXNzaW9ucyI6eyJwdWIiOnt9LCJzdWIiOnt9fSwiYXV0aG9yaXphdGlvbiI6e30sInR5cGUiOiJhY2NvdW50IiwidmVyc2lvbiI6Mn19.WmfBUZ6dmH5gQBKmB6GtBPEDWbv9pCP83rOoukdNzS_TwmcM-aBOtizwVaoWmoU8EATw21neLmph-8RnoN-GBg


natsBox:
  enabled: false
