apiVersion: cilium.io/v2
kind: CiliumBGPPeerConfig
metadata:
  name: nadia-ipv4
spec:
  authSecretRef: nadia-bgp-auth
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          advertise: fruktsallad-pod-cidrs
