[[helm]]
namespace = "argo"
release = "argocd"
values = "argo/values.yaml"

[[helm]]
namespace = "rook-ceph"
release = "rook"
values = "rook-ceph/rook-ceph-values.yaml"

[[helm]]
namespace = "rook-ceph"
release = "csi-drivers"
values = "rook-ceph/csi-drivers-values.yaml"
extra-resources = "rook-ceph/extra"

[[copy]]
namespace = "acme-dns"
source = "acme-dns/manifests"
config = {"/etc/acme-dns/config.cfg" = "acme-dns/config.cfg"}

[[helm]]
namespace = "cert-manager"
release = "cert-manager"
values = "cert-manager/values.yaml"
extra-resources = "cert-manager/extra"

[[helm]]
namespace = "cert-manager"
release = "trust-manager"

[[helm]]
namespace = "envoy-gateway-system"
release = "envoy-gateway"
values = "envoy-gateway/values.yaml"
extra-resources = "envoy-gateway/extra"

[[helm]]
namespace = "metrics-server"
release = "metrics-server"

[[helm]]
namespace = "grafana"
release = "grafana-operator"
extra-resources = "grafana/extra"
values = "grafana/values.yaml"

[[helm]]
namespace = "kubelet-csr-approver"
release = "kubelet-csr-approver"

[[website]]
name = "zq.lu"
namespace = "web"
hugo-repo = "https://github.com/nresare/zq.lu"

[[website]]
name = "noa.re"
namespace = "web"
hugo-repo = "https://github.com/nresare/noa.re"
extra-hostnames = "nadia.resare.com"
