[[helm]]
namespace = "kube-system"
release = "cilium"
values = "cilium/values.yaml"
extra-resources = "cilium/extra"

[[helm]]
namespace = "argo"
release = "argocd"
values = "argo/values.yaml"

[[helm]]
namespace = "rook-ceph"
release = "rook"
values = "rook-ceph/rook-ceph-values.yaml"

[[helm]]
namespace = "rook-ceph"
release = "csi-drivers"
values = "rook-ceph/csi-drivers-values.yaml"
extra-resources = "rook-ceph/extra"

[[copy]]
namespace = "acme-dns"
source = "acme-dns/manifests"
config = {"/etc/acme-dns/config.cfg" = "acme-dns/config.cfg"}

[[helm]]
namespace = "cert-manager"
release = "cert-manager"
values = "cert-manager/values.yaml"
extra-resources = "cert-manager/extra"

[[helm]]
namespace = "cert-manager"
release = "trust-manager"

[[helm]]
namespace = "envoy-gateway-system"
release = "envoy-gateway"
values = "envoy-gateway/values.yaml"
extra-resources = "envoy-gateway/extra"

[[helm]]
namespace = "metrics-server"
release = "metrics-server"

[[helm]]
namespace = "grafana"
release = "grafana-operator"
extra-resources = "grafana/extra"
values = "grafana/values.yaml"

[[helm]]
namespace = "kubelet-csr-approver"
release = "kubelet-csr-approver"

[[website]]
name = "zq.lu"
namespace = "web"
hugo-repo = "https://github.com/nresare/zq.lu"

[[website]]
name = "noa.re"
namespace = "web"
hugo-repo = "https://github.com/nresare/noa.re"
extra-hostnames = "nadia.resare.com"

[[helm]]
namespace = "surrealdb"
release = "surrealdb"
values = "surrealdb/values.yaml"

[[simple]]
namespace = "idmouse"
image = "nresare/idmouse"
extra-resources = "idmouse/extra"
k8s-role = "idmouse-signing-keys"
config = {"/config/idmouse.toml" = "idmouse/idmouse.toml"}

[[website]]
name = "k8s.noa.re"
namespace = "jwksproxy"
image = "nresare/jwksproxy:0.2.0"
replicas = 1
config = { "/config/jwksproxy.toml" = "jwksproxy/jwksproxy.toml" }

[[website]]
name = "repo.noa.re"
replicas = 2
namespace = "reposnake"
image = "nresare/reposnake:0.2.1"
args = ["-c", "/config/reposnake.toml"]
config = { "/config/reposnake.toml" = "reposnake/reposnake.toml" }
custom-token-audiences = ["idmouse", "sts.amazonaws.com"]
emptydir-path = "/var/tmp"

[website.env]
AWS_STS_REGIONAL_ENDPOINTS = "regional"
AWS_REGION = "eu-west-2"
AWS_ENDPOINT_URL = "http://rook-ceph-rgw-fruktsallad.rook-ceph.svc"
AWS_ROLE_ARN = "arn:aws:iam:::role/reposnake"
AWS_WEB_IDENTITY_TOKEN_FILE = "/var/run/secrets/tokens/sts.amazonaws.com"

[[helm]]
namespace = "teleport-cluster"
release = "teleport-cluster"
values = "teleport/cluster-values.yaml"
extra-resources = "teleport/extra"

[[helm]]
namespace = "teleport"
release = "teleport-kube-agent"
values = "teleport/agent-values.yaml"

[[helm]]
namespace = "mimir"
release = "mimir"
values = "mimir/values.yaml"

[[helm]]
namespace = "loki"
release = "loki"
values = "loki/values.yaml"

[[helm]]
namespace = "alloy"
release = "alloy"
values = "alloy/metrics.yaml"
config = {"metrics.cfg" = "alloy/metrics.cfg"}
extra-resources = "alloy/metrics-extra"

[[helm]]
namespace = "alloy"
name-override = "alloy-log-forwarder"
release = "alloy"
values = "alloy/log-forwarder.yaml"
config = {"log-forwarder.cfg" = "alloy/log-forwarder.cfg"}

[[helm]]
namespace = "nats"
release = "nats"
values = "nats/values.yaml"

[[helm]]
namespace = "nats"
release = "nack"
skip-crds = true
values = "nats/nack-values.yaml"
extra-resources = "nats/extra"
custom-token-audiences = ["nats"]

[[copy]]
namespace = "nats"
source = "nats/crds"

[[simple]]
name = "nats-aws-auth"
namespace = "nats"
replicas = 1
image = "nresare/nats-aws-auth:v2026.02.19-1de79ca-12-gafc222e"
config = {"/config/nats-aws-auth.toml" = "nats/nats-aws-auth.toml"}
external-secret = "/keys"
args = [
    "--url=nats://nats.nats",
    "--auth-backend=k8s-oidc",
    "--jwt-issuer=https://k8s.noa.re",
    "--config=/config/nats-aws-auth.toml",
    "--key-storage=directory",
    "--key-dir=/keys"
]

[[website]]
name = "relcoord.noa.re"
namespace = "relcoord"
replicas = 2
image = "{{relcoord_image}}"
config = {"/config/relcoord.toml" = "relcoord/relcoord.toml"}
custom-token-audiences = ["idmouse", "idcat.noa.re"]

[[website]]
name = "idcat.noa.re"
namespace = "idcat"
image = "public.ecr.aws/portswigger-platform/idcat:934b43e7"
replicas = 2
args = ["--debug"]
external-secrets = ["/app-keys"]
config = { "/config/idcat.toml" = "idcat/idcat.toml" }
custom-token-audiences = ["nats"]

[[helm]]
namespace = "randomsecret"
release = "randomsecret"
