[[helm]]
namespace = "argo"
release = "argocd"
values = "argo/values.yaml"

[[helm]]
namespace = "rook-ceph"
release = "rook"
values = "rook-ceph/rook-ceph-values.yaml"

[[helm]]
namespace = "rook-ceph"
release = "csi-drivers"
values = "rook-ceph/csi-drivers-values.yaml"
extra-resources = "rook-ceph/extra"