bind_address = "0.0.0.0:8080"
origin = "http://idmouse.idmouse.svc"
signing_key_storage = "kubernetes_secret"

[[role]]
name = "idelephant-source"
audience = "idmouse"
issuer = "https://k8s.noa.re"

[role.claims]
sub = "system:serviceaccount:idelephant:default"

[[role]]
name = "reposnake-source"
audience = "idmouse"
issuer = "https://k8s.noa.re"

[role.claims]
sub = "system:serviceaccount:reposnake:default"

[[role]]
name = "relcoord-source"
audience = "idmouse"
issuer = "https://k8s.noa.re"

[role.claims]
sub = "system:serviceaccount:relcoord:default"

[[mapping]]
name = "idelephant"
role = "idelephant-source"
[mapping.additional_claims]
ns = "default"
db = "idelephant"
ac = "idelephant"
rl = ["Editor"]

[[mapping]]
name = "reposnake"
role = "reposnake-source"
[mapping.additional_claims]
ns = "default"
db = "reposnake"
ac = "reposnake"
rl = ["Editor"]

[[mapping]]
name = "relcoord"
role = "relcoord-source"
[mapping.additional_claims]
ns = "default"
db = "relcoord"
ac = "relcoord"
rl = ["Editor"]
