listen = "0.0.0.0"
port = 8080
log-level = "INFO"

[nats]
servers = ["nats://nats.nats.svc"]
name = "webhook-poker"  # client name shown in NATS server connection listings
token-path = "/var/run/secrets/tokens/nats"

[[target]]
name = "argo"
url = "http://argocd-server.argo.svc/api/webhook"

[[subscription]]
name = "argo-poker"
stream = "github-events"
targets = ["argo"]
headers = { X-GitHub-Event = "push" }
