server:
  service:
    annotations:
      teleport.dev/port: http
      teleport.dev/name: argo
    labels:
      noa.re/discover: enabled
configs:
  params:
    server.insecure: true
    #controller.diff.server.side: true
    reposerver.max.combined.directory.manifests.size: '30M'
dex:
  enabled: false
