server:
  service:
    annotations:
      teleport.dev/port: http
      teleport.dev/name: argo
    labels:
      noa.re/discover: enabled
configs:
  cm:
    oidc.config: |
      name: idelephant
      issuer: https://id.noa.re
      clientId: argo-fruktsallad
      clientSecret: ignored
      enablePKCEAuthentication: true
      requestedScopes:
       - openid
       - profile
       - email

  params:
    server.insecure: true
    #controller.diff.server.side: true
    reposerver.max.combined.directory.manifests.size: '30M'
dex:
  enabled: false
