apiVersion: v1
kind: ConfigMap
metadata:
  name: unifi-backend-ca
  namespace: envoy-gateway-system
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDNTCCAh2gAwIBAgIJYCYANmy6HyAIMA0GCSqGSIb3DQEBCwUAMBYxFDASBgNV
    BAMTC3VuaWZpLmxvY2FsMB4XDTI2MDgxNTEzMDg0MFoXDTI4MTExNzEzMDg0MFow
    FjEUMBIGA1UEAxMLdW5pZmkubG9jYWwwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAw
    ggEKAoIBAQC364C4BJDxE/Pb0M6V5Mbrm9YwC5gmnL9k26mO4IK+JCTsQcRC1moa
    gx4Ckt98GX16NGfTTLdS9MzhV4BcqPyt2z2l35fch2ny5YJDPlH6iceLl8xuhsCK
    Y1A/MbwbRrNSP/RbaOAPCTeVLpgN5bmJ76oyzcwPeW9QY14/S7hVqprmH4dpYWOy
    lPoUZFy51epkvGThPcpXL924rVkmTHEYEh3SMqRZHrp0tgupSGD3724MpmZQLWa2
    CqTMIc8OYzGWfbwAO+xJLttMCmC/cqF+r4VhNIVzj8rRf7UXtOQBwsPt9/IrpY+E
    eplLsjOBNwY2FzGh0aP79p6X8JpPxyEbAgMBAAGjgYUwgYIwCwYDVR0PBAQDAgL0
    MDEGA1UdJQQqMCgGCCsGAQUFBwMBBggrBgEFBQcDAgYIKwYBBQUHAwMGCCsGAQUF
    BwMIMEAGA1UdEQQ5MDeCC3VuaWZpLmxvY2Fsgglsb2NhbGhvc3SCBVs6OjFdhwR/
    AAABhxD+gAAAAAAAAAAAAAAAAAABMA0GCSqGSIb3DQEBCwUAA4IBAQAUlAGTvXjL
    8J6rdy3DYZCY0V00MKh4sVRpxkSUSLgKQdPoksJa1ECeXM+QbcJc58o/vPPKKCAF
    0swxzQiCuSWnj3j/gLzSvA1y4iKWhICGNe9ymraDfMbmwV2oaYQshvWFosKDaBNw
    vM+dAUPOopdlltjUV2X6j+zhY98o7fMnqYLXHRmsMg7CYG5ZA1lGZUV7Ap+h4lss
    xwz2Z1AlZO9Lpn+Cw3UgCF2BxXcOETdVsNOqTr+bUAFa2ivIhguJb755xsZd+oDk
    n9eY1KgtSZOr20hbPp73aN9fv0xKIc9N9jPYgr1eE1GJEVNLiFJzVOaj7SCTUPcS
    EzT4iW2a+GK3
    -----END CERTIFICATE-----
