apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: custom-proxy-config
spec:
  mergeGateways: true
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 2
      envoyService:
        type: NodePort
        externalTrafficPolicy: Cluster
        patch:
          type: JSONMerge
          value:
            spec:
              ports:
                - name: https-443
                  port: 443
                  protocol: TCP
                  targetPort: 10443
                  nodePort: 31071
                - name: https-443-udp
                  port: 443
                  protocol: UDP
                  targetPort: 10443
                  nodePort: 31071
